"""add saved_plans

Revision ID: e2efd1f7bfd6
Revises: 3dcf84ff7b8b
Create Date: 2026-02-24 16:39:16.628548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2efd1f7bfd6'
down_revision: Union[str, Sequence[str], None] = '3dcf84ff7b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shopping_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('formatted_output', sa.Text(), nullable=True),
    sa.Column('formatted_recipes_output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['app_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_plans_session_id'), 'saved_plans', ['session_id'], unique=False)
    op.create_index(op.f('ix_saved_plans_user_id'), 'saved_plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_plans_user_id'), table_name='saved_plans')
    op.drop_index(op.f('ix_saved_plans_session_id'), table_name='saved_plans')
    op.drop_table('saved_plans')
    # ### end Alembic commands ###
